

```{r}
# Se leen los genes expresados diferencialmente obtenidos tras realizar el metaanálisis presentes en todas las muestras de sangre y cerebro
all_females <- read.table(file = "Results/MA/Contrastes_alfa_0.05/0_Contrastes todos/1_Females/sig.genes.df.txt",
                     header = T, 
                     sep = "\t")

symbol_all_females <- all_females$ID

all_ASD_control <- read.table(file = "Results/MA/Contrastes_alfa_0.05/0_Contrastes todos/3_ASD vs Control/sig.genes.df.txt",
                     header = T, 
                     sep = "\t")

symbol_all_ASD_control <- all_ASD_control$ID


all_ASD_sex <- read.table(file = "Results/MA/Contrastes_alfa_0.05/0_Contrastes todos/4_Female_ASD vs Male_ASD/sig.genes.df.txt",
                     header = T, 
                     sep = "\t")

symbol_all_ASD_sex <- all_ASD_sex$ID
```

```{r}
# Se leen los genes expresados diferencialmente obtenidos tras realizar el metaanálisis presentes en el cerebro
arrays_females <- read.table(file = "Results/MA/Contrastes_alfa_0.05/1_Contrastes sin RNAseq/1_Females/sig.genes.df.txt",
                     header = T, 
                     sep = "\t")

symbol_arrays_females <- arrays_females$ID

array_ASD_control <- read.table(file = "Results/MA/Contrastes_alfa_0.05/1_Contrastes sin RNAseq/3_ASD vs control/sig.genes.df.txt",
                     header = T, 
                     sep = "\t")

symbol_array_ASD_control <- array_ASD_control$ID


```

```{r}
# Se leen los genes expresados diferencialmente obtenidos tras realizar el metaanálisis presentes en la sangre
sangre_ASD_control <- read.table(file = "Results/MA/Contrastes_alfa_0.05/3_Contraste_sangre_arrays+rnaseq/3_ASD vs Control/sig.genes.df.txt",
                     header = T, 
                     sep = "\t")

symbol_sangre_ASD_control <- sangre_ASD_control$ID
```

```{r}
# Se leen los genes expresados diferencialmente obtenidos tras realizar el metaanálisis presentes en el cerebro
cerebro_females <- read.table(file = "Results/MA/Contrastes_alfa_0.05/4_Contraste_cerebro_arrays+rnaseq/1_Males/sig.genes.df.txt",
                     header = T, 
                     sep = "\t")

symbol_cerebro_females <- cerebro_females$ID

cerebro_ASD_control <- read.table(file = "Results/MA/Contrastes_alfa_0.05/4_Contraste_cerebro_arrays+rnaseq/3_ASD vs control/sig.genes.df.txt",
                     header = T, 
                     sep = "\t")

symbol_cerebro_ASD_control <- cerebro_ASD_control$ID


cerebro_ASD_sex <- read.table(file = "Results/MA/Contrastes_alfa_0.05/4_Contraste_cerebro_arrays+rnaseq/4_Female_ASD vs Male_ASD/sig.genes.df.txt",
                     header = T, 
                     sep = "\t")

symbol_cerebro_ASD_sex <- cerebro_ASD_sex$ID
```


```{r}
# Comunes entre las muestras de sangre y cerebro en ASD_control
symbol_comunes <- symbol_sangre_ASD_control[symbol_sangre_ASD_control %in% symbol_cerebro_ASD_control]
cat("Comunes en ASD_control entre las muestras de sangre y cerebro:", "\n\t> ", symbol_comunes, 0, "\n\n")

# Comunes entre las muestras de sangre y todas las muestras en ASD_control
symbol_comunes <- symbol_sangre_ASD_control[symbol_sangre_ASD_control %in% symbol_all_ASD_control]
cat("Comunes en sangre y todas las muestras:", "\n\t> ", symbol_comunes, "\n\n")

# Comunes entre las muestras de cerebro y todas las muestras en ASD_control
symbol_comunes <- symbol_cerebro_ASD_control[symbol_cerebro_ASD_control %in% symbol_all_ASD_control]
cat("Comunes en cerebro y todas las muestras:", "\n\t> ", symbol_comunes, "\n\n")

```

```{r}
# Comunes entre las muestras de cerebro y totales en Females
symbol_comunes <- symbol_cerebro_females[symbol_cerebro_females %in% symbol_all_females]
cat("Comunes en ASD_control entre las muestras de sangre y cerebro:", "\n\t> ", symbol_comunes, "\n\n")


```
```{r}
# Comunes entre las muestras de cerebro y totales en Females
symbol_comunes <- symbol_cerebro_ASD_sex[symbol_cerebro_ASD_sex %in% symbol_all_ASD_sex]
cat("Comunes en ASD_control entre las muestras de sangre y cerebro:", "\n\t> ", symbol_comunes, "\n\n")
```


```{r}
for (i in symbol_all_ASD_control){
  cat(i, "\n")
}

```


------------------------------------------------------


```{r}
# Se leen los genes expresados diferencialmente obtenidos tras realizar el metaanálisis presentes en todas las muestras de sangre y cerebro
all_females <- read.table(file = "Results/MA/Contrastes_alfa_0.1/0_Contrastes todos/1_Females/sig.genes.df.txt",
                     header = T, 
                     sep = "\t")

symbol_all_females <- all_females$ID

all_ASD_control <- read.table(file = "Results/MA/Contrastes_alfa_0.1/0_Contrastes todos/3_ASD vs Control/sig.genes.df.txt",
                     header = T, 
                     sep = "\t")

symbol_all_ASD_control <- all_ASD_control$ID


all_ASD_sex <- read.table(file = "Results/MA/Contrastes_alfa_0.1/0_Contrastes todos/4_Female_ASD vs Male_ASD/sig.genes.df.txt",
                     header = T, 
                     sep = "\t")

symbol_all_ASD_sex <- all_ASD_sex$ID
```

```{r}
# Se leen los genes expresados diferencialmente obtenidos tras realizar el metaanálisis presentes en la sangre
sangre_ASD_control <- read.table(file = "Results/MA/Contrastes_alfa_0.1/3_Contraste_sangre_arrays+rnaseq/3_ASD vs Control/sig.genes.df.txt",
                     header = T, 
                     sep = "\t")

symbol_sangre_ASD_control <- sangre_ASD_control$ID
```

```{r}
# Se leen los genes expresados diferencialmente obtenidos tras realizar el metaanálisis presentes en el cerebro
cerebro_females <- read.table(file = "Results/MA/Contrastes_alfa_0.1/4_Contraste_cerebro_arrays+rnaseq/1_Males/sig.genes.df.txt",
                     header = T, 
                     sep = "\t")

symbol_cerebro_females <- cerebro_females$ID

cerebro_ASD_control <- read.table(file = "Results/MA/Contrastes_alfa_0.1/4_Contraste_cerebro_arrays+rnaseq/3_ASD vs control/sig.genes.df.txt",
                     header = T, 
                     sep = "\t")

symbol_cerebro_ASD_control <- cerebro_ASD_control$ID


cerebro_ASD_sex <- read.table(file = "Results/MA/Contrastes_alfa_0.1/4_Contraste_cerebro_arrays+rnaseq/4_Female_ASD vs Male_ASD/sig.genes.df.txt",
                     header = T, 
                     sep = "\t")

symbol_cerebro_ASD_sex <- cerebro_ASD_sex$ID
```

```{r}
# Comunes entre las muestras de sangre y cerebro en ASD_control
symbol_comunes <- symbol_sangre_ASD_control[symbol_sangre_ASD_control %in% symbol_cerebro_ASD_control]
cat("Comunes en ASD_control entre las muestras de sangre y cerebro:", "\n\t> ", symbol_comunes, 0, "\n\n")

# Comunes entre las muestras de sangre y todas las muestras en ASD_control
symbol_comunes <- symbol_sangre_ASD_control[symbol_sangre_ASD_control %in% symbol_all_ASD_control]
cat("Comunes en sangre y todas las muestras:", "\n\t> ", symbol_comunes, "\n\n")

# Comunes entre las muestras de cerebro y todas las muestras en ASD_control
symbol_comunes <- symbol_cerebro_ASD_control[symbol_cerebro_ASD_control %in% symbol_all_ASD_control]
cat("Comunes en cerebro y todas las muestras:", "\n\t> ", symbol_comunes, "\n\n")

```
```{r}
# Comunes entre las muestras de cerebro y totales en Females
symbol_comunes <- symbol_cerebro_females[symbol_cerebro_females %in% symbol_all_females]
cat("Comunes en ASD_control entre las muestras de sangre y cerebro:", "\n\t> ", symbol_comunes, "\n\n")


```
```{r}
# Comunes entre las muestras de cerebro y totales en Females
symbol_comunes <- symbol_cerebro_ASD_sex[symbol_cerebro_ASD_sex %in% symbol_all_ASD_sex]
cat("Comunes en ASD_control entre las muestras de sangre y cerebro:", "\n\t> ", symbol_comunes, "\n\n")
```

```{r}
for (i in symbol_all_ASD_control){
  cat(i, "\n")
}

```

-------------

En esta seccions e comprueba si los dos genes DE en la sangre, estan presentes en todos los genes de cerebro para ver cómo ha sido el resultado

```{r}
cerebro_ASD_sex <- read.table(file = "Results/MA/Contrastes_alfa_0.05/4_Contraste_cerebro_arrays+rnaseq/4_Female_ASD vs Male_ASD/sig.genes.df.txt",
                              header = TRUE,
                              sep = "\t")

sangre_ASD_sex <- read.table(file = "Results/MA/Contrastes_alfa_0.05/3_Contraste_sangre_arrays+rnaseq/all.genes.tsv",
                             header = TRUE,
                             sep = "\t")
symbol_sangre_ASD_sex <- rownames(sangre_ASD_sex)
sangre_ASD_sex$ID <- symbol_sangre_ASD_sex

#symbol_cerebro_ASD_sex <- rownames(cerebro_ASD_sex)
symbol_cerebro_ASD_sex <- cerebro_ASD_sex$ID
#cerebro_ASD_sex$ID <- symbol_cerebro_ASD_sex

comunes <- intersect(symbol_sangre_ASD_sex, symbol_cerebro_ASD_sex)

tabla_cerebro <- cerebro_ASD_sex
tabla_sangre <- sangre_ASD_sex[sangre_ASD_sex$ID %in% comunes, ]
tabla_final <- merge(tabla_cerebro, tabla_sangre, by = "ID")

```

